#List of rules https://github.com/realm/SwiftLint/blob/master/Rules.md
disabled_rules: # rule identifiers to exclude from running
  - trailing_closure
  - explicit_acl
  - explicit_top_level_acl
  - explicit_self
  - explicit_type_interface
  - explicit_enum_raw_value
  - fallthrough
  - file_header
  - force_unwrapping
  - force_cast
  - extension_access_modifier
  - multiline_function_chains
  - multiline_parameters_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - nslocalizedstring_require_bundle
  - number_separator
  - missing_docs
  - redundant_type_annotation
  - required_deinit
  - trailing_comma
  - trailing_whitespace
  - nesting
  - object_literal
  - implicit_return
  - implicitly_unwrapped_optional
  - type_contents_order
  - strict_fileprivate
  - conditional_returns_on_newline
  - closure_body_length
  - cyclomatic_complexity
  - function_body_length
  - untyped_error_in_catch
  - todo
  - reduce_into
  - multiline_arguments_brackets
  - function_default_parameter_at_end

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - attributes
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_body_length
  - closure_parameter_position
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - comma
  - compiler_protocol_init
  - contains_over_first_not_nil
  - control_statement
  - convenience_type
  - cyclomatic_complexity
  - deployment_target
  - discarded_notification_center_observer
  - discouraged_direct_init
  - discouraged_object_literal
  - duplicate_imports
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fatal_error_message
  - file_length
  - file_name
  - first_where
  - for_where
  - force_try
  - function_body_length
  - function_default_parameter_at_end
  - function_parameter_count
  - generic_type_name
  - identical_operands
  - identifier_name
  - implicit_getter
  - inert_defer
  - is_disjoint
  - joined_default_parameter
  - large_tuple
  - last_where
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_multiple
  - legacy_nsgeometry_functions
  - legacy_random
  - let_var_whitespace
  - line_length
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - mark
  - modifier_order
  - multiline_literal_brackets
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - nimble_operator
  - no_fallthrough_only
  - notification_center_detachment
  - nslocalizedstring_key
  - nsobject_prefer_isequal
  - opening_brace
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_over_fileprivate
  # - prohibited_interface_builder
  - prohibited_super_call
  - protocol_property_accessors_order
  - reduce_boolean
  - reduce_into
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - required_enum_case
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_first_last
  - sorted_imports
  - statement_position
  - static_operator
  - strong_iboutlet
  - switch_case_alignment
  - switch_case_on_newline
  - syntactic_sugar
  - toggle_bool
  - trailing_newline
  - trailing_semicolon
  - type_body_length
  - type_name
  - unavailable_function
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_declaration
  - unused_enumerated
  - unused_import
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - void_return
  - weak_delegate
  - yoda_condition
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Senat
  - SNUtils
  - SNAnalytics
  - SenatTests
  - SNNetwork
  - SNStorages
  - SNDomain
  - SNLog
  - incredible_trata

excluded:
  - Pods
  - Carthage
  - AirWatch
  - Senat/Modules/FaceRecognition/SmartBio
  - incredible_trataTests
  - incredible_trataUITests

identifier_name:
  min_length: 2
  max_length:
    warning: 70
    error: 80
  excluded:
    - "x"
    - "y"
    - "i"

line_length: 140

type_body_length:
  warning: 750
  error: 750

file_length:
  warning: 1500
  error: 1500

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - "ID"
    - "IDs"
    - "Map"

function_parameter_count:
  warning: 10
  error: 12

#function_body_length:
#  warning: 300
#  error: 300

# implicitly_unwrapped_optional:
#   severity: warning

reporter: "xcode"
